CREATE TABLE analytical_retail_rebate.rr_agreement_signatory_product_rebate_detail_test1103 (
    version_no character varying(1000) ENCODE lzo,
    year integer ENCODE raw,
    quarter character varying(10) ENCODE lzo,
    group_name character varying(1000) ENCODE lzo,
    distributor_type character varying(1000) ENCODE lzo,
    second_party_level_1_distributor_code character varying(1000) ENCODE lzo,
    second_party_level_1_distributor_standard_name character varying(1000) ENCODE lzo,
    agreement_signatory_code character varying(1000) ENCODE lzo,
    agreement_signatory_name character varying(1000) ENCODE lzo,
    brand_code character varying(1000) ENCODE lzo,
    brand_name character varying(1000) ENCODE lzo,
    product_code character varying(1000) ENCODE lzo,
    product_name character varying(1000) ENCODE lzo,
    poa_rebate_deductible numeric(38, 6) ENCODE az64,
    poa_rebate_actual_cap_rate numeric(38, 6) ENCODE az64,
    poa_rebate_payment_cap_rate numeric(38, 6) ENCODE az64,
    poa_rebate_calculation_status character varying(10) ENCODE lzo,
    single_product_poa_rebate_coefficient numeric(38, 6) ENCODE az64,
    poa_rebate_coefficient numeric(38, 6) ENCODE az64,
    single_product_poa_actual_rebate_points numeric(38, 6) ENCODE az64,
    single_product_poa_payment_rebate_points numeric(38, 6) ENCODE az64,
    poa_offtake_sellin_assessment_dimension character varying(10) ENCODE lzo,
    poa_offtake_sellin_assessment_ratio_skutotal numeric(38, 6) ENCODE az64,
    poa_offtake_amount numeric(38, 6) ENCODE az64,
    poa_sellin_amount numeric(38, 6) ENCODE az64,
    poa_offtake_sellin_assessment_ratio numeric(38, 6) ENCODE az64,
    poa_target_amount numeric(38, 6) ENCODE az64,
    poa_achievement_amount numeric(38, 6) ENCODE az64,
    poa_achievement_rate numeric(38, 6) ENCODE az64,
    total_achievement_poa_rate_lq numeric(38, 6) ENCODE az64,
    unpaid_poa_rebata_ytd_q3 numeric(38, 6) ENCODE az64,
    poa_actual_rebate_coefficient numeric(38, 6) ENCODE az64,
    poa_payment_rebate_coefficient numeric(38, 6) ENCODE az64,
    poa_actual_rebate numeric(38, 6) ENCODE az64,
    poa_payment_rebate numeric(38, 6) ENCODE az64,
    display_fee numeric(38, 6) ENCODE az64,
    disease_science_fee numeric(38, 6) ENCODE az64,
    care_coupon_qty integer ENCODE raw,
    care_coupon_amount numeric(38, 6) ENCODE az64,
    insert_dt timestamp without time zone ENCODE az64,
    insert_user character varying(1000) ENCODE lzo,
    update_dt timestamp without time zone ENCODE az64,
    update_user character varying(1000) ENCODE lzo
) DISTSTYLE AUTO
SORTKEY
    (year);
	
	
CREATE TABLE analytical_retail_rebate.rr_data_amount_detail_monthly (
    version_no character varying(1000) ENCODE lzo,
    year integer ENCODE az64,
    month integer ENCODE az64,
    quarter character varying(1000) ENCODE lzo,
    region_name character varying(1000) ENCODE lzo,
    province_name character varying(1000) ENCODE lzo,
    group_name character varying(1000) ENCODE lzo,
    distributor_level character varying(1000) ENCODE lzo,
    agreement_signatory_code character varying(1000) ENCODE lzo,
    agreement_signatory_name character varying(1000) ENCODE lzo,
    agreement_type character varying(1000) ENCODE lzo,
    distributor_type character varying(1000) ENCODE lzo,
    chain_headquarter_code character varying(1000) ENCODE lzo,
    chain_headquarter_name character varying(1000) ENCODE lzo,
    second_party_level_1_distributor_code character varying(1000) ENCODE lzo,
    second_party_level_1_distributor_standard_name character varying(1000) ENCODE lzo,
    level_1_distributor_subsidiary_code character varying(1000) ENCODE lzo,
    level_1_distributor_subsidiary_name character varying(1000) ENCODE lzo,
    fourth_party_t1_procurement_header_code character varying(1000) ENCODE lzo,
    fourth_party_t1_procurement_header_name character varying(1000) ENCODE lzo,
    is_shared_warehouse character varying(1000) ENCODE lzo,
    shared_warehouse_signatory_code character varying(1000) ENCODE lzo,
    shared_warehouse_signatory_name character varying(1000) ENCODE lzo,
    store_delivery_company_code character varying(1000) ENCODE lzo,
    store_delivery_company_name character varying(1000) ENCODE lzo,
    shared_warehouse_with_level_1_distributor character varying(1000) ENCODE lzo,
    product_code character varying(1000) ENCODE lzo,
    product_name character varying(1000) ENCODE lzo,
    product_name_en character varying(1000) ENCODE lzo,
    brand_code character varying(1000) ENCODE lzo,
    brand_name character varying(1000) ENCODE lzo,
    brand_name_en character varying(1000) ENCODE lzo,
    is_strategic_product character varying(1000) ENCODE lzo,
    ex_price numeric(38, 6) ENCODE az64,
    target_qty numeric(38, 6) ENCODE az64,
    target_amount numeric(38, 6) ENCODE az64,
    offtake_qty numeric(38, 6) ENCODE az64,
    offtake_amount numeric(38, 6) ENCODE az64,
    sellin_amount numeric(38, 6) ENCODE az64,
    total_store_sellin_amount numeric(38, 6) ENCODE az64,
    fix_store_amount numeric(38, 6) ENCODE az64,
    n_specify_hq_sellin_amount numeric(38, 6) ENCODE az64,
    n_specify_hq_store_amount numeric(38, 6) ENCODE az64,
    insert_dt timestamp without time zone ENCODE az64,
    insert_user character varying(1000) ENCODE lzo,
    update_dt timestamp without time zone ENCODE az64,
    update_user character varying(1000) ENCODE lzo,
    n_restricted_store_sellin_amount numeric(38, 6) ENCODE az64
) DISTSTYLE AUTO;